all: section_a section_b section_c

section_a:
	$(MAKE) -C section_a

section_b:
	$(MAKE) -C section_b

section_c:
	$(MAKE) -C section_c

clean:
	$(MAKE) -C section_a clean
	$(MAKE) -C section_b clean
	$(MAKE) -C section_c clean
